=== neeraj5d5/HTML/xsd/Books.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="books" type="xs:string">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="year" type="xs:string">
                <xs:complexType>
                <xs:attribute name="type" type="xs:string" use="required"/>
                    <xs:sequence>
                        <xs:element name="semister" type="xs:string">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="book" type="xs:string">
                                        <xs:complexType>
                                            <xs:sequence>
                                                 <xs:element name="name" type="xs:string"/>
                                                 <xs:element name="edition" type="xs:string"/>
                                                 <xs:element name="bookrelease" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>

                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

=== neeraj5d5/HTML/xsd/xsdBooks.xml
<books xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="Books.xsd">
    <year type="1999">
        <semister>
            <book>
                <name>Compiler Design</name>
                <edition>2nd</edition>
                <bookrelease> 1999 </bookrelease>
            </book>
            <book>
                <name>Unix programming</name>
                <edition>2nd</edition>
                <bookrelease> 1999 </bookrelease>
            </book>
            <book> 
                <name> OOAD </name>
                <edition>2nd</edition>
                <bookrelease> 1999 </bookrelease>
            </book>
            <book>
                <name> DMBS </name>
                <edition>2nd</edition>
                <bookrelease>2011 </bookrelease>
            </book>
            <book>
                <name> PEHV </name>
                <edition>3rd</edition>
                <bookrelease>2011 </bookrelease>
            </book>
        </semister>
        <semister>
            <book>
                <name>Computer Networks</name>
                <edition>4th</edition>
                <bookrelease>2011 </bookrelease>
            </book>
            <book>
                <name> DWM </name>
               <edition>5th</edition>
                <bookrelease>2011 </bookrelease>
            </book>
            <book> 
                <name> DAA </name>
               <edition>6th</edition>
                <bookrelease>2011 </bookrelease>
            </book>
            <book>
                <name> STM </name>
               <edition>4th</edition>
                <bookrelease> 2011</bookrelease>
            </book>
            <book>
                <name> Cyber Security </name>
                <edition>8th</edition>
                <bookrelease> 2011</bookrelease>
            </book>
        </semister>
    </year >
</books>
