=== neeraj5d5/HTML/xsd/marks.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="marks" type="xs:string">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="year" type="xs:string">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sem" type="xs:string">
                            <xs:complexType>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="sem" type="xs:string"/>
                                <xs:element name="branch" type="xs:string"/>
                                <xs:element name="midmarks" type="xs:string">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="sub" type="xs:integer"/>  
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="lab" type="xs:string">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="internal" type="xs:integer"/>
                                            <xs:element name="external" type="xs:integer"/>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="cgpa" type="xs:integer"/>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

=== neeraj5d5/HTML/xsd/xsdmarks.xml
<marks xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="marks.xsd">
    <year>
        <sem>
            <name>varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>65</sub>
                <sub>45</sub>
                <sub>54</sub>
                <sub>45</sub>
                <sub>45</sub>
            </midmarks>
            <lab>
                <internal> 45 </internal>
                <external> 45 </external>
            </lab>
            <cgpa> 7 </cgpa>
        </sem>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>45</sub>
                <sub>34</sub>
                <sub>65</sub>
                <sub>56</sub>
                <sub>56</sub>
            </midmarks>
            <lab>
                <internal> 30 </internal>
                <external> 30 </external>
            </lab>
            <cgpa> 7 </cgpa>
        </sem>
    </year>
    <year>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>20</sub>
                <sub>25</sub>
                <sub>25</sub>
                <sub>20</sub>
                <sub>20</sub>
            </midmarks>
            <lab>
                <internal> 30 </internal>
                <external> 20 </external>
            </lab>
            <cgpa> 6 </cgpa>
        </sem>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>20</sub>
                <sub>30</sub>
                <sub>30</sub>
                <sub>25</sub>
                <sub>25</sub>
            </midmarks>
            <lab>
                <internal> 25 </internal>
                <external> 25 </external>
            </lab>
            <cgpa> 7 </cgpa>
        </sem>
    </year>
    <year>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>20</sub>
                <sub>30</sub>
                <sub>15</sub>
                <sub>30</sub>
                <sub>30</sub>
            </midmarks>
            <lab>
                <internal> 30 </internal>
                <external> 25 </external>
            </lab>
            <cgpa> 5 </cgpa>
        </sem>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>20</sub>
                <sub>30</sub>
                <sub>30</sub>
                <sub>30</sub>
                <sub>15</sub>
            </midmarks>
            <lab>
                <internal> 25 </internal>
                <external> 25 </external>
            </lab>
            <cgpa> 7 </cgpa>
        </sem>
    </year>
    <year>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>35</sub>
                <sub>35</sub>
                <sub>75</sub>
                <sub>55</sub>
                <sub>55</sub>
            </midmarks>
            <lab>
                <internal> 68 </internal>
                <external> 26 </external>
            </lab>
            <cgpa> 5 </cgpa>
        </sem>
        <sem>
            <name>Varma</name>
            <college>SASI</college>
            <branch>CSE</branch>
            <midmarks>
                <sub>50</sub>
                <sub>20</sub>
                <sub>65</sub>
                <sub>65</sub>
                <sub>65</sub>
            </midmarks>
            <lab>
                <internal> 30 </internal>
                <external> 15 </external>
            </lab>
            <cgpa> 7 </cgpa>
        </sem>
    </year>
</marks>
