=== neeraj5d5/HTML/xsd/table.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="timetable" type="xs:string">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="day" type="xs:string">
                <xs:complexType>
                <xs:attribute name="type" type="xs:string" use="required"/>
                    <xs:sequence>
                        <xs:element name="period1" type="xs:string" />
                        <xs:element name="period2" type="xs:string" />
                        <xs:element name="period3" type="xs:string" />
                        <xs:element name="period4" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

=== neeraj5d5/HTML/xsd/xsdTable.xml
<timetable xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:schemaLocation="table.xsd">
    <day type="monday">
        <period1>ads</period1>
        <period2>cs</period2>
        <period3>cd</period3>
        <period4>m1</period4>
    </day>
    <day type="tuesday">
        <period1>ads</period1>
        <period2>m1</period2>
        <period3>wt</period3>
        <period4>cs</period4>
    </day>
    <day type="wednesday">
        <period1>cc</period1>
        <period2>mc</period2>
        <period3>english</period3>
        <period4>cs</period4>
    </day>
    <day type="thursday">
        <period1>wt</period1>
        <period2>cc</period2>
        <period3>m1</period3>
        <period4>m1</period4>
    </day>
    <day type="friday">
        <period1>m1</period1>
        <period2>ads</period2>
        <period3>mc</period3>
        <period4>cc</period4>
    </day>
    <day type="saturday">
        <period1>cc</period1>
        <period2>cs</period2>
        <period3>wt</period3>
        <period4>m1</period4>
    </day>
    
</timetable>
